### ISSUE TITLE
Reference External Content

### ISSUE THREAD

**Issue by cybercamphackathon** [s3curitybug/guardedbox#19]
Please include a reference to those pieces of code that were extracted from a third party.
For example, if you included a library from a third party, please reference that third party. If you adapted a piece of code, please reference that it was inspired in the piece of code.

**Comment by s3curitybug** [comment]
Backend libraries are at https://github.com/s3curitybug/guardedbox/blob/master/pom.xml in the dependencies section.

Frontend libraries are at https://github.com/s3curitybug/guardedbox/blob/master/front/package.json in the dependencies and devDependencies section.
