### ISSUE TITLE
Buenas prácticas para proyectos OSS

### ISSUE THREAD

**Issue by cr0hn** [s3curitybug/guardedbox#2]
Sería deseable seguir las buenas prácticas para proyectos OSS publicados.

Se puede encontrar un guía en: https://opensource.guide

A modo de resumen, sería deseable que el proyecto tuviera los siguientes archivos, en caso de no tenerlos, (con el contenido adecuado):

- CONTRIBUTING
- LICENSE
- README
- .gitignore
- ISSUE_TEMPLATE/issue_template.md
- TODO

Del mismo modo, sería deseable (en caso de no tenerlo) que el repositorio tuviera:
- *labels* a modo de palabras clave del mismo.
- Una descripción del proyecto

**Comment by s3curitybug** [comment]
Gracias cr0hn, me pongo a ello en cuanto sea posible.

**Comment by s3curitybug** [comment]
Resuelto.
