### ISSUE TITLE
CryptoCaptchaService doesn't stop spammers from signup

### ISSUE THREAD

**Issue by Wocanilo** [s3curitybug/guardedbox#20]
Proof of Work captchas doesn't stop spammers. If a home computer can compute it fast enough, a spammer can with tens of VPS.

No one pays for CPU load, so the economic cost is really low for an attacker.

We recommend another approach to the problem. For example, text captchas in a browser, not in the app, so it cant stole the user master password.

**Comment by s3curitybug** [comment]
Thanks for tips!

The cryptocaptcha is not for the login process. That one has its own protections (signed challenge response and OTP). It is to avoid email spam in the register process.
